name: BizCentrix
favicon: null
layout_spectrum: 0.60731
typography_spectrum: 0.65212
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f1f1f1'
    - '#000000'
    - '#b41112'
    - '#565656'
    - '#bf9292'
  brandStrength: 0.7969261661637574
  lightness: 0.0625
  saturation: 0.125
  rhythmicContrast: 0.75
purpose: []
